name: example
description: A new Flutter project.
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc_rest_api:
    path: ..

  cupertino_icons: ^1.0.0
  equatable: ^2.0.3
  flutter_bloc: ^7.0.1
  http: ^0.13.3
  hydrated_bloc: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
