name: bloc_rest_api
description: A generic bloc package to implement REST APIs easily in flutter.
version: 0.4.0+1
homepage: https://github.com/muhammadidrees/bloc_rest_api

environment: 
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.3
  flutter_bloc: ^7.0.1
  http: ^0.13.3
  hydrated_bloc: ^7.0.1
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.10
  pedantic: ^1.11.1
  bloc_test: ^8.0.2
  path_provider: ^2.0.2

flutter: