name: bloc_rest_api
description: A generic bloc package to implement REST APIs easily in flutter.
version: 0.3.1
homepage: https://github.com/muhammadidrees/bloc_rest_api

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^1.2.5
  flutter_bloc: ^6.1.3
  http: ^0.12.2
  hydrated_bloc: ^6.1.0
  meta: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.3
  pedantic: ^1.9.2

flutter: