name: bloc_rest_api
description: A generic package to implement REST APIs easily in flutter.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^1.2.5
  flutter_bloc: ^6.1.1
  http: ^0.12.2
  hydrated_bloc: ^6.1.0
  meta: ^1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: